name: ЁЯЪА FTP Deploy

on:
  push:
    branches:
      - main  # main ржмрзНрж░рж╛ржЮрзНржЪрзЗ push ржХрж░рж▓рзЗ trigger рж╣ржмрзЗ

jobs:
  ftp-deploy:
    name: ЁЯУд Upload via FTP
    runs-on: ubuntu-latest

    steps:
      - name: ЁЯФД Checkout code
        uses: actions/checkout@v4

      - name: ЁЯУБ Upload to FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.4.0
        with:
          server: ftpupload.net
          username: b33_39554238
          password: nokhil22
          protocol: ftp
          port: 21
          server-dir: /htdocs/  # ржПржЦрж╛ржирзЗ ржЖржкржирж┐ ржЖржкржирж╛рж░ FTP ржлрзЛрж▓рзНржбрж╛рж░ ржжрж┐рждрзЗ ржкрж╛рж░рзЗржи
          local-dir: ./              # ржЖржкржирж╛рж░ ржкрзНрж░ржЬрзЗржХрзНржЯрзЗрж░ ржХрзЛржи ржлрзЛрж▓рзНржбрж╛рж░ ржЖржкрж▓рзЛржб рж╣ржмрзЗ