name: ЁЯЪА FTP Deploy

on:
  push:
    branches:
      - main  # main ржмрзНрж░рж╛ржЮрзНржЪрзЗ push ржХрж░рж▓рзЗ trigger рж╣ржмрзЗ

jobs:
  ftp-deploy:
    name: ЁЯУд Upload via FTP
    runs-on: ubuntu-latest

    steps:
      - name: ЁЯФД Checkout code
        uses: actions/checkout@v4

      - name: ЁЯУБ Upload to FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ftpupload.net
          username: b33_39554238
          password: nokhil22
          protocol: ftp
          port: 21
          server-dir: /htdocs/     # ржлрж╛ржЗрж▓ржЧрзБрж▓рзЛ ржПржЦрж╛ржирзЗ ржЖржкрж▓рзЛржб рж╣ржмрзЗ (public_html/htdocs)
          local-dir: ./            # ржПржЗ рж▓рзЛржХрж╛рж▓ ржлрзЛрж▓рзНржбрж╛рж░ ржерзЗржХрзЗ ржлрж╛ржЗрж▓ ржирзЗржУрзЯрж╛ рж╣ржмрзЗ